name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set git config
        run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: "https://npm.pkg.github.com"
          scope: "@ou-ca"

      - name: Install Yarn globally
        run: npm install -g yarn

      - name: Bump version
        run: yarn version patch

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Copy updated package.json
        if: github.event_name == 'push'
        run: yarn run deployPrePublish

      - name: Update project version
        if: github.event_name == 'push'
        run: git push --follow-tags

      - name: Publish
        if: github.event_name == 'push'
        run: yarn npm publish dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GPR_TOKEN}}
